upload:
  path: /upload
  controller: SwooleCSVHandler\Upload\Infrastructure\Communication\Http\Controller\UploadController::postUpload
  methods: POST

index:
  path: /
  controller: SwooleCSVHandler\Upload\Infrastructure\Communication\Http\Controller\UploadController::getIndex
  methods: GET

process:
  path: /handle
  controller: SwooleCSVHandler\CsvHandler\Infrastructure\Communication\Http\Controller\CsvHandlerController::getHandleCsv
  methods: GET

entries:
  path: /entries
  controller: SwooleCSVHandler\Entries\Infrastructure\Communication\Http\Controller\EntriesController::getEntries
  methods: GET